### ISSUE TITLE
FE 바텀시트 컴포넌트 분리

### ISSUE THREAD

**Issue by yook-jongho** [softeerbootcamp-3rd/Team2-iFive#98]
바텀시트 컴포넌트 분리

**분리 이유**
- 기존 바텀시트에서 유저정보를 props로 받아 분기처리를 진행
- 분기처리해야할 경우의 수가 많아짐에 따라 분기로직 복잡도 상승
- 따라서 부모의 바텀시트와 기사의 바텀시트를 각각의 컴포넌트로 분리

**구현 내용**
- [x] 바텀시트 분리
    - 바텀시트 기본 템플릿
    - 내부 콘텐츠 분리 (부모, 기사에 따라 보여지는 내용이 다름)
- [x] 부모 바텀시트 구현
- [x] 기사 바텀시트 구현

**Comment by Sang-minKIM** [comment]
이슈 꼼꼼하고 좋네요!
